### PR TITLE
Haskell extraction

### PR DESCRIPTION
**Pull request by AHartNtkn**
This implements the code necessary to extract to Haskell and run that extraction. The Nix stuff will have to be done by someone else.

### CODE REVIEW

**Review by MatthewCroughan — APPROVED** [review]
Nix changes look fine.

Can you explain more of what you want done regarding Nix? What is "The Nix stuff" you're referring to?

**Comment by AHartNtkn** [comment]
Right now, the file `Tinyram_VM.hs` in `/src` is generated by `Extraction.v` in `/theories`. When `dune build` is run, that file will be created in the `/_build` directory, and I manually moved it into `/src`. Morgan doesn't like that and wants that process to be automated somehow by Nix.

To build the .hs files requires cabal and GHC (see the cabal commands in the README files in the main and `/src` folders), but not any libraries beyond base. The current `.flake` file doesn't include GHC, Cabal, etc, so that needs to be added. Whether everything is still built through Cabal doesn't matter so much; if there's some other command that works better for Nix would be up to whoever.

**Comment by morganthomas** [comment]
@MatthewCroughan , I added more Nix changes to build the Coq code, extract it to Haskell, and build that Haskell, in Nix. Please re-review the Nix changes.

**Comment by nixinator** [comment]
@nixinator @DarthPJB @MatthewCroughan will take a look see when we have a moment.

**Pull request merged**
